CHANGELOG.md
package.json
public/settings.html
public/stylesheets/settings_style.css
src/frontend/settings/components/App.tsx
src/frontend/settings/components/SettingsForm.tsx
src/frontend/settings/components/SettingsSaveButton.tsx
src/frontend/settings/components/Tag.tsx
src/frontend/settings/components/TagContainer.tsx
src/frontend/settings/index.tsx
webpack.config.js

Add Settings page

---

package-lock.json
public/stylesheets/SidePannel.css
public/stylesheets/style.css
src/AppRouter.tsx
src/frontend/share/components/FriendList.tsx
src/frontend/share/components/MenuItem.tsx
src/frontend/share/components/Sidebar.tsx

Unify Styling

---

CHANGELOG.md
package-lock.json
package.json
src/frontend/shared/components/FriendsPanel.tsx
src/frontend/shared/components/NavigationItems.tsx

add_friend_item_to_menu_bar

---

CHANGELOG.md
codecov.yml
package-lock.json
package.json
src/App.ts
src/backend/api/index.ts
src/backend/api/v1/Chats.ts
src/backend/api/v1/index.ts
test/backend/api/v1/ChatTest.spec.ts

Add api routers

---

codecov.yml

add patch default

---

CHANGELOG.md
package.json
src/AppRouter.tsx
src/frontend/login_register/components/Login.tsx
src/frontend/login_register/components/Register.tsx

Login Register UI (Only UI) and APPRouter Change accordingly

---

CHANGELOG.md
package.json

This will fix the issue that sometimes test files cannot be find.

Update test command

---

.travis.yml
CHANGELOG.md
codecov.yml
package-lock.json
package.json
src/App.ts
src/backend/Models.ts
src/backend/api/v1/Chats.ts
test/backend/TestNonExistAPI.ts
test/backend/api/v1/ChatTest.spec.ts

Connect chat to mongodb

---

CHANGELOG.md
package.json
src/backend/api/v1/Users.ts
test/backend/api/v1/UserTest.spec.ts

add patch for userRouter

---

CHANGELOG.md
package.json
src/backend/api/v1/Comments.ts
src/backend/api/v1/Posts.ts
src/backend/api/v1/Users.ts
src/backend/api/v1/index.ts
src/backend/models/CommentModel.ts
src/backend/models/PostModel.ts
src/backend/models/UserModel.ts
src/backend/shared/IAppError.ts
src/backend/shared/Middlewares.ts
test/backend/api/v1/CommentTest.spec.ts
test/backend/api/v1/PostTest.spec.ts

add APIs for post page

---

CHANGELOG.md
package.json
src/backend/api/v1/Chats.ts
src/backend/api/v1/Comments.ts
src/backend/api/v1/Posts.ts
src/backend/api/v1/Users.ts
src/backend/models/ChatModel.ts
src/backend/models/CommentModel.ts
src/backend/models/PostModel.ts
src/backend/models/TagModel.ts
src/backend/models/UserModel.ts
src/frontend/chat_room/Actions/index.ts
src/frontend/shared/globleFunctions.ts
src/shared/ModelInterfaces.ts
test/backend/api/v1/ChatTest.spec.ts

modify models and move to shared folder

---

CHANGELOG.md
package.json
src/backend/api/v1/Tags.ts
src/backend/api/v1/index.ts
test/backend/api/v1/TagTest.spec.ts

Add Tags apis

---

CHANGELOG.md
package.json
public/stylesheets/chat_room_style.css
src/frontend/chat_room/Actions/index.ts
src/frontend/chat_room/components/App.tsx
src/frontend/chat_room/components/ChatRoomBubbles.tsx
src/frontend/chat_room/components/ChatRoomChatArea.tsx
src/frontend/chat_room/reducer/index.ts
src/frontend/posts_page/components/UserBlock.tsx
src/frontend/shared/components/FriendsPanel.tsx
src/frontend/shared/components/FriendsPanelItem.tsx
src/frontend/shared/interfaces/IUserProps.tsx

Fix chat frontend

---

CHANGELOG.md
package-lock.json
package.json
public/stylesheets/posts_page_style.css
src/backend/api/v1/Posts.ts
src/backend/api/v1/Users.ts
src/backend/models/PostModel.ts
src/backend/models/UserModel.ts
src/frontend/posts_page/actions/index.tsx
src/frontend/posts_page/components/CommentInputBar.tsx
src/frontend/posts_page/components/ComponentsContainer.tsx
src/frontend/posts_page/components/HomePage.tsx
src/frontend/posts_page/components/InputBlock.tsx
src/frontend/posts_page/components/PersonalPage.tsx
src/frontend/posts_page/components/PostBlock.tsx
src/frontend/posts_page/components/SearchBlock.tsx
src/frontend/posts_page/components/TextInputEditor.tsx
src/frontend/posts_page/components/UserBlock.tsx
src/frontend/settings/actions/index.tsx
src/frontend/settings/components/App.tsx
src/frontend/settings/components/ProfileFriendBlock.tsx
src/frontend/settings/components/ProfilePostBlock.tsx
src/frontend/settings/components/SettingsForm.tsx
src/frontend/settings/components/SettingsProfilePhoto.tsx
src/frontend/settings/components/TagContainer.tsx
src/frontend/settings/components/UserProfile.tsx
src/frontend/settings/reducers/index.tsx
src/frontend/shared/components/NavigationItems.tsx
src/frontend/shared/globleFunctions.ts
test/backend/api/v1/UserTest.spec.ts

A lot of features added and updated, frontend nearly meets all minimum and standandard requirements

---

CHANGELOG.md
package.json
src/backend/api/v1/Posts.ts
src/backend/api/v1/Users.ts
src/frontend/posts_page/components/HomePage.tsx
src/frontend/posts_page/components/SearchBlock.tsx
src/frontend/shared/globleFunctions.ts
test/backend/api/v1/PostTest.spec.ts
test/backend/api/v1/UserTest.spec.ts

add search for post and user

---

CHANGELOG.md
package.json
src/frontend/chat_room/Actions/index.ts
src/frontend/posts_page/components/CommentInputBar.tsx
src/frontend/posts_page/components/PostBlock.tsx
src/frontend/posts_page/components/TextInputEditor.tsx
src/frontend/posts_page/components/UserBlock.tsx
src/frontend/settings/components/SettingsForm.tsx
src/frontend/settings/components/SettingsProfilePhoto.tsx
src/frontend/shared/Networks.ts
src/frontend/shared/components/NavigationBar.tsx
src/frontend/shared/globleFunctions.ts

Add helper function to get alert if error when having API Call

---

CHANGELOG.md
package.json

Add Prod build

---

README.md

Update ReadingMe to include descriptions

---

src/backend/api/v1/Comments.ts
src/backend/api/v1/Posts.ts

Add Json response

---

CHANGELOG.md
package-lock.json
src/frontend/posts_page/components/PostBlock.tsx

fix hide post bug

---

CHANGELOG.md
package-lock.json
package.json
public/stylesheets/posts_page_style.css
public/stylesheets/settings_style.css
src/frontend/posts_page/components/TextInputEditor.tsx
src/frontend/posts_page/components/UserBlock.tsx
src/frontend/settings/components/ProfilePostBlock.tsx
src/frontend/settings/components/SettingsProfilePhoto.tsx
src/frontend/settings/components/UserProfile.tsx
src/frontend/shared/globleFunctions.ts

Fix some bugs

---

CHANGELOG.md
package.json
public/stylesheets/style.css
src/AppRouter.tsx
src/backend/api/v1/Chats.ts
src/backend/models/ChatModel.ts
src/frontend/chat_room/Actions/index.ts
src/frontend/chat_room/components/ChatRoomBubbles.tsx
src/frontend/chat_room/components/ChatRoomChatArea.tsx
src/frontend/chat_room/reducer/index.ts
src/frontend/shared/Networks.ts
src/frontend/shared/components/FriendsPanel.tsx
src/frontend/shared/components/FriendsPanelItem.tsx
src/frontend/shared/globleFunctions.ts
src/shared/ModelInterfaces.ts
src/shared/SocketEvents.ts
test/backend/api/v1/ChatTest.spec.ts

Add notifications

---

CHANGELOG.md
package-lock.json
package.json
public/stylesheets/posts_page_style.css
src/frontend/posts_page/components/CommentInputBar.tsx
src/frontend/posts_page/components/HomePage.tsx
src/frontend/posts_page/components/PersonalPage.tsx
src/frontend/posts_page/components/PostBlock.tsx
src/frontend/posts_page/components/TextInputEditor.tsx

Fixed some bugs, deleted unused buttons

---

CHANGELOG.md
package.json
src/frontend/chat_room/Actions/index.ts

Fix all Chats are Sent

---

CHANGELOG.md
package.json
src/App.ts

Fix socket connection

---

CHANGELOG.md
README.md
package-lock.json
package.json
public/stylesheets/chats_page_style.css
public/stylesheets/style.css
src/backend/api/v1/Users.ts
src/frontend/chats_page/components/App.tsx
src/frontend/chats_page/components/ChatBlock.tsx
src/frontend/chats_page/components/CreateGroupForm.tsx
src/frontend/chats_page/components/FriendBlock.tsx
src/frontend/posts_page/components/PersonalPage.tsx
src/frontend/posts_page/components/PostBlock.tsx
src/frontend/posts_page/components/UserBlock.tsx
src/frontend/settings/components/ProfileFriendBlock.tsx
src/frontend/settings/components/UserProfile.tsx
src/frontend/settings/reducers/index.tsx
src/frontend/shared/components/FriendsPanelItem.tsx
src/frontend/shared/globleFunctions.ts
test/backend/api/v1/UserTest.spec.ts

Group Chat Styling and fix some bugs

---

CHANGELOG.md
package-lock.json
package.json
public/stylesheets/posts_page_style.css
public/stylesheets/settings_style.css
src/frontend/chats_page/components/ChatList.tsx
src/frontend/posts_page/components/CommentInputBar.tsx
src/frontend/posts_page/components/CommentsContainer.tsx
src/frontend/posts_page/components/ComponentsContainer.tsx
src/frontend/posts_page/components/TextInputEditor.tsx
src/frontend/settings/components/TagContainer.tsx
src/frontend/settings/components/UserProfile.tsx
src/frontend/settings/components/UserTimeTable.tsx

Fix warnings, console log, text input editor styling
